rootProject.name = "common-libs"

include("common-messages")
include("common-message-core")
include("common-validation")
include("common-sqs")
include("common-webclient")
include("common-secret-manager")
include("common-cache")
include("validation-consumer-demo")
include("common-database")
include("common-s3file")
include("common-notification-history")
include("common-notification-template")
include("common-notification")
