common:
  database:
    host: localhost
    port: 5432
    name: inventory_db
    schema: public
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    cleanup-retention-years: 2
    rotate-enabled: true
    rotate-scan-interval: 20s
