# Header names
webclient.header-name.request-id=X-Request-Id
webclient.header-name.user-context=X-User-Context
webclient.header-name.client-ip=X-Client-Ip

# Header inheritance lists
webclient.inherited-headers.web=X-Request-Id,X-Correlation-Id,X-User-Context,X-Client-Ip
webclient.inherited-headers.batch=X-Request-Id,X-Correlation-Id
